name: Release
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['src/**']
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v7
      - name: Publish features
        uses: devcontainers/action@v1
        with:
          publish-features: 'true'
          base-path-to-features: './src'
          generate-docs: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
